# Generated by Django 4.2.4 on 2023-11-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_agencies_agencyaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agencies',
            old_name='name',
            new_name='fullname',
        ),
        migrations.AddField(
            model_name='agencies',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
