# Generated by Django 4.2.4 on 2023-11-06 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_name_agencies_fullname_agencies_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agencies',
            new_name='Barangay',
        ),
        migrations.RenameField(
            model_name='barangay',
            old_name='agencyAddress',
            new_name='barangayAddress',
        ),
        migrations.RenameField(
            model_name='barangay',
            old_name='agencyName',
            new_name='barangayName',
        ),
    ]
